name: healpix-cookbook-dev2
channels:
  - conda-forge
dependencies:
  - aiohttp
  - cmocean
  - easygems
  - healpix
  - intake
  - intake-esm
  - intake-stac
  - intake-xarray
  - jupyter-book
  - jupyterlab
  - uxarray
  - zarr
  - mystmd
